import "./globals.css";
import NavBar from "../../UI/NavBar";

export const metadata = {
  title: "Productive 101",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col  items-center text-black`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
